export const ui = {
  headerArt: document.getElementById('header-art'),
  skinToggler: document.querySelector('#skin-toggler'),
  appContainer: document.getElementById('app'),
  recordBtn: document.querySelector('#record-btn'),
  stopRecordBtn: document.querySelector('#stop-record-btn'),
  downloadBtn: document.querySelector('#download-btn'),
  masterVolume: document.querySelector('#master-volume'),
  headphoneVolume: document.querySelector('#headphone-volume'),
  crossfader: document.querySelector('.crossfader'),
  fxChorus: document.querySelector('#fx-chorus'),
  fxReverb: document.querySelector('#fx-reverb'),
  fxDelay: document.querySelector('#fx-delay'),
  samplerPads: document.querySelector('.sampler-pads'),
  channelA: {
    container: document.querySelector('#channel-a'),
    tracklist: document.querySelector('#channel-a .tracklist'),
    selectDirectory: document.querySelector('#channel-a .select-directory'),
    selectedPath: document.querySelector('#channel-a .selected-path'),
    playBtn: document.querySelector('#channel-a .play-btn'),
    stopBtn: document.querySelector('#channel-a .stop-btn'),
    cueBtn: document.querySelector('#channel-a .cue-btn'),
    timeSlider: document.querySelector('#channel-a .time-slider'),
    timeCurrent: document.querySelector('#channel-a .time-current'),
    timeRemaining: document.querySelector('#channel-a .time-remaining'),
    volumeSlider: document.querySelector('#channel-a .volume-slider'),
    tempoSlider: document.querySelector('#channel-a .tempo-slider'),
    tempoLabel: document.querySelector('#channel-a .tempo-label'),
    eqLow: document.querySelector('#eq-low-a'),
    eqMid: document.querySelector('#eq-mid-a'),
    eqHigh: document.querySelector('#eq-high-a'),
  },
  channelB: {
    container: document.querySelector('#channel-b'),
    tracklist: document.querySelector('#channel-b .tracklist'),
    selectDirectory: document.querySelector('#channel-b .select-directory'),
    selectedPath: document.querySelector('#channel-b .selected-path'),
    playBtn: document.querySelector('#channel-b .play-btn'),
    stopBtn: document.querySelector('#channel-b .stop-btn'),
    cueBtn: document.querySelector('#channel-b .cue-btn'),
    timeSlider: document.querySelector('#channel-b .time-slider'),
    timeCurrent: document.querySelector('#channel-b .time-current'),
    timeRemaining: document.querySelector('#channel-b .time-remaining'),
    volumeSlider: document.querySelector('#channel-b .volume-slider'),
    tempoSlider: document.querySelector('#channel-b .tempo-slider'),
    tempoLabel: document.querySelector('#channel-b .tempo-label'),
    eqLow: document.querySelector('#eq-low-b'),
    eqMid: document.querySelector('#eq-mid-b'),
    eqHigh: document.querySelector('#eq-high-b'),
  },
  visualizer: document.getElementById('visualizer'),
};
